apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
        - name: stock-api
          image: courselabs/stock-api:1.0.0
          ports:
            - containerPort: 5000
