{
 "title": "Widgetario",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, method, instance) (http_requests_in_progress{job=\"web\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"web\"}[5m]))"
    }
   ]
  },
  {
   "title": "90th Percentile Response",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(code, job, method, instance) (rate(http_request_duration_seconds_bucket{job=\"web\", code=\"200\"}[5m])))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"web\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"web\"}[5m]))"
    }
   ]
  },
  { "title": "Stock API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average Response Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_seconds_sum{job=\"stock-api\"}) without (job, instance)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=\"stock-api\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory In Use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"stock-api\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"stock-api\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Products API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Average Response Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds_sum{job=\"products-api\"}) without(exception, job, method, outcome, status, instance)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Database Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{job=\"products-api\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"products-api\"}) without(area, id)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"products-api\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}