apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: courselabs/products-api:1.0.0
          ports:
            - containerPort: 8080
env:
- name: DB_HOST
  valueFrom:
    configMapKeyRef:
      name: products-api-config
      key: DB_HOST
- name: DB_PORT
  valueFrom:
    configMapKeyRef:
      name: products-api-config
      key: DB_PORT
- name: DB_NAME
  valueFrom:
    configMapKeyRef:
      name: products-api-config
      key: DB_NAME
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: products-db-secret
      key: POSTGRES_USER
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: products-db-secret
      key: POSTGRES_PASSWORD

